# Generated by Django 4.1.7 on 2024-05-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_book_price_client_books_alter_client_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
